name: dim_client
description: DIM demo.
version: 1.0.8
homepage: https://github.com/dimpart/demo-dart
repository: https://github.com/dimpart/demo-dart
issue_tracker: https://github.com/dimpart/demo-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6

  object_key: ^1.1.1
  lnc: ^1.2.1
#  startrek: ^1.1.1
  stargate: ^1.1.0
#  dimp: ^2.1.1
  dimsdk: ^2.1.2
  dim_plugins: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
