name: dim_client
description: DIM demo.
version: 1.0.4
homepage: https://github.com/dimchat/demo-dart
repository: https://github.com/dimchat/demo-dart
issue_tracker: https://github.com/dimchat/demo-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  object_key: ^1.1.0
  lnc: ^1.1.0
#  startrek: ^1.1.0
  stargate: ^1.0.0
#  dimp: ^2.1.1
  dimsdk: ^2.1.1
  dim_plugins: ^2.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
