name: dim_client
description: DIM demo.
version: 0.1.0-dev.8
homepage: https://github.com/dimchat/demo-dart
repository: https://github.com/dimchat/demo-dart
issue_tracker: https://github.com/dimchat/demo-dart/issues

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

# Add regular dependencies here.
dependencies:
  dimp: ^0.1.0-dev.6
  dimsdk: ^0.1.0-dev.7
  dim_plugins: ^0.1.0-dev.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
