name: dim_client
description: DIM demo.
version: 0.7.4
homepage: https://github.com/dimchat/demo-dart
repository: https://github.com/dimchat/demo-dart
issue_tracker: https://github.com/dimchat/demo-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  object_key: ^0.1.1
  lnc: ^0.1.2
#  startrek: ^0.5.2
  stargate: ^0.5.2
#  dimp: ^1.2.1
  dimsdk: ^1.2.1
  dim_plugins: ^1.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
